using System.Collections.Generic;
namespace TFFCC_Save_Editor
{
    public class Databases
    {

        public static string[] monsters = new string[]
        {
            "Goblin (Small)",
            "Lich",
            "Behemoth",
            "Iron Giant (Original Blue)",
            "Iron Giant (Red)",
            "Black Knight",
            "Captain",
            "Emperor",
            "Hein",
            "Xande",
            "Cloud of Darkness",
            "Scarmiglione",
            "Cagnazzo",
            "Barbariccia",
            "Rubicante",
            "Golbez",
            "Zeromus",
            "Gilgamesh",
            "Enkidu",
            "objet d'Art",
            "ExDeath",
            "Deathgaze",
            "Ultros",
            "Kefka Palazzo",
            "Hill Gigas",
            "Magitek Armor",
            "Typhon",
            "Kefka",
            "Jenova - SYNTHESIS",
            "Safer - Sephiroth",
            "Reno",
            "Gesper",
            "PuPu",
            "Esthar Soldier",
            "Gigantuar",
            "Tonberry King",
            "Edea",
            "Ultimecia",
            "Trance Kuja",
            "Necron",
            "Black Waltz No. 3",
            "Ozma",
            "Anima",
            "Seymour Natus",
            "Braska's Final Aeon",
            "Goblin (Big)",
            "Gigas",
            "The Shadow Lord",
            "Goobbue",
            "Eald'narche",
            "Bangaa Thief",
            "Gabranth",
            "Mandragoras",
            "The undying",
            "PSICOM Enforcer",
            "Manasvin Warmech",
            "Admantoise",
            "Orphan",
            "Chaos",
            "Omega",
            "Shinryu",
            "Ultima Weapon",
            "Diamond Weapon",
            "Yiazmat",
            "Colossus",
            "Ultima, the High Seraph",
            "Manikin",
            "Feral Chaos",
            "Atlas",
            "Bahamut SIN",
            "Magic Pot",
            "Tonberry",
            "Cactuar",
            "Ahriman (Original Yellow)",
            "Ahriman (Green)",
            "Ahriman (Blue)",
            "Ahriman (Red)",
            "Ahriman (Purple)",
            "Malboro (Original Green)",
            "Malboro (Yellow)",
            "Malboro (Blue)",
            "Malboro (Purple)",
            "Flan (Original Blue)",
            "Flan (Green)",
            "Flan (Yellow)",
            "Flan (Orange)",
            "Flan (Purple)",
            "Bomb (Original Red)",
            "Bomb (Green)",
            "Bomb (Blue)",
            "Bomb (Purple)",
            "Green Dragon",
            "Lamia (Original Red)",
            "Lamia (Green)",
            "Lamia (Orange)",
            "Lamia (Purple)",
            "Lamia (Light Purple)",
            "Sahagin (Original Green)",
            "Sahagin (Blue)",
            "Sahagin (Light Purple)",
            "Sahagin (Pink)",
            "Sahagin (Purple)",
            "Coeurl (Original Orange)",
            "Coeurl (Blue)",
            "Coeurl (Yellow)",
            "Coeurl (Red)",
            "Sand Worm (Original Yellow)",
            "Sand Worm (Green)",
            "Sand Worm (Teal)",
            "Sand Worm (Red)",
            "Sand Worm (Purple)",
            "Zu (Original Black)",
            "Zu (Green)",
            "Zu (Blue)",
            "Zu (Brown)",
            "Zu (Beige)",
            "Mover",
            "Great Malboro (Original Green)",
            "Great Malboro (Yellow)",
            "Great Malboro (Blue)",
            "Great Malboro (Purple)",
            "Jumbo Flan (Original Blue)",
            "Jumbo Flan (Green)",
            "Jumbo Flan (Yellow)",
            "Jumbo Flan (Orange)",
            "Jumbo Flan (Purple)",
            "King Bomb (Original Red)",
            "King Bomb (Green)",
            "King Bomb (Blue)",
            "King Bomb (Purple)",
            "King Behemoth (Original Purple)",
            "King Behemoth (Brown)",
            "King Behemoth (Black)",
            "King Behemoth (Green)",
            "King Behemoth (Maroon)"
        };

        public static List<string> items = new List<string>
        {
            "Potion",
            "Hi-Potion",
            "X-Potion",
            "Elixir",
            "Phoenix Down",
            "Phoenix Pinion",
            "Light Curtain",
            "Hero Drink",
            "Mog's Amulet",
            "Ribbon",
            "Giant's Tonic",
            "Bucchus's Cider",
            "Sage's Wisdom",
            "Hermes Sandals",
            "Iron Draft",
            "Saint's Spirit",
            "Growth Egg",
            "Miratete's Memoirs",
            "Molulu's Charm",
            "Rumah's Magicite",
            "Shiva's Magicite",
            "Ifrit's Magicite",
            "Odin's Magicite",
            "Bahamat's Magicite",
            "Knights' Magicite",
            "Shuriken",
            "Fuma Shuriken",
            "Antarctic Wind",
            "Bomb Fragement",
            "Zeus's Wrath",
            "Brigand's Gloves",
            "Tantal Greens",
            "Gysahl Greens",
            "Sylkis Green",
            "Pendant",
            "Gysahl Whistle",
            "Siren",
            "Gnomish Bread",
            "Teleport Stone",
            "Tent",
            "Jeweled Ring",
            "Fortune Sphere",
            "Gambler's Spirit",
            "LevelDown Nut",
            "Scapegoat",
            "Crimson Crest Key",
            "Thunder Crest Key",
            "Crystal Crest Key",
            "Dark Crest Key",
            "Economy Class Ticket",
            "First Class Ticket",
            "Curaga Scroll",
            "Pray Scroll I",
            "Pray Scroll II",
            "Pray Scroll III",
            "Brace Scroll I",
            "Brace Scroll II",
            "Brace Scroll III",
            "Recall Scroll",
            "EXP Up Scroll I",
            "EXP Up Scroll II",
            "EXP Up Scroll III",
            "EXP Hound Scroll",
            "Pillager's Tome",
            "Millionaire's Tome",
            "Flare Scroll V",
            "Thief's Tome",
            "Kupo Nut Recipe",
            "Runner's Tome",
            "Cura Scroll",
            "Mighty Guard Scroll",
            "Elegy Scroll I",
            "Elegy Scroll II",
            "Elegy Scroll III",
            "Berserk Scroll I",
            "Berserk Scroll II",
            "Berserk Scroll III",
            "Meteor Scroll",
            "Ultima Scroll",
            "Doomsday Scroll",
            "Brawler Scroll I",
            "Brawler Scroll II",
            "Brawler Scroll III",
            "Cry Scroll I",
            "Cry Scroll II",
            "Cry Scroll III",
            "Scare Scroll",
            "Chocobo Cure Scroll",
            "Move-HP Up Scroll",
            "Libra Scroll I",
            "Libra Scroll II",
            "Libra Scroll III",
            "#001 [N] CollectaCard",
            "#001 [R] CollectaCard",
            "#001 [P] CollectaCard",
            "#002 [N] CollectaCard",
            "#002 [R] CollectaCard",
            "#002 [P] CollectaCard",
            "#003 [N] CollectaCard",
            "#003 [R] CollectaCard",
            "#003 [P] CollectaCard",
            "#004 [N] CollectaCard",
            "#004 [R] CollectaCard",
            "#004 [P] CollectaCard",
            "#005 [N] CollectaCard",
            "#005 [R] CollectaCard",
            "#005 [P] CollectaCard",
            "#006 [N] CollectaCard",
            "#006 [R] CollectaCard",
            "#006 [P] CollectaCard",
            "#007 [N] CollectaCard",
            "#007 [R] CollectaCard",
            "#007 [P] CollectaCard",
            "#008 [N] CollectaCard",
            "#008 [R] CollectaCard",
            "#008 [P] CollectaCard",
            "#009 [N] CollectaCard",
            "#009 [R] CollectaCard",
            "#009 [P] CollectaCard",
            "#010 [N] CollectaCard",
            "#010 [R] CollectaCard",
            "#010 [P] CollectaCard",
            "#011 [N] CollectaCard",
            "#011 [R] CollectaCard",
            "#011 [P] CollectaCard",
            "#012 [N] CollectaCard",
            "#012 [R] CollectaCard",
            "#012 [P] CollectaCard",
            "#013 [N] CollectaCard",
            "#013 [R] CollectaCard",
            "#013 [P] CollectaCard",
            "#014 [N] CollectaCard",
            "#014 [R] CollectaCard",
            "#014 [P] CollectaCard",
            "#015 [N] CollectaCard",
            "#015 [R] CollectaCard",
            "#015 [P] CollectaCard",
            "#016 [N] CollectaCard",
            "#016 [R] CollectaCard",
            "#016 [P] CollectaCard",
            "#017 [N] CollectaCard",
            "#017 [R] CollectaCard",
            "#017 [P] CollectaCard",
            "#018 [N] CollectaCard",
            "#018 [R] CollectaCard",
            "#018 [P] CollectaCard",
            "#019 [N] CollectaCard",
            "#019 [R] CollectaCard",
            "#019 [P] CollectaCard",
            "#020 [N] CollectaCard",
            "#020 [R] CollectaCard",
            "#020 [P] CollectaCard",
            "#021 [N] CollectaCard",
            "#021 [R] CollectaCard",
            "#021 [P] CollectaCard",
            "#022 [N] CollectaCard",
            "#022 [R] CollectaCard",
            "#022 [P] CollectaCard",
            "#023 [N] CollectaCard",
            "#023 [R] CollectaCard",
            "#023 [P] CollectaCard",
            "#024 [N] CollectaCard",
            "#024 [R] CollectaCard",
            "#024 [P] CollectaCard",
            "#025 [N] CollectaCard",
            "#025 [R] CollectaCard",
            "#025 [P] CollectaCard",
            "#026 [N] CollectaCard",
            "#026 [R] CollectaCard",
            "#026 [P] CollectaCard",
            "#027 [N] CollectaCard",
            "#027 [R] CollectaCard",
            "#027 [P] CollectaCard",
            "#028 [N] CollectaCard",
            "#028 [R] CollectaCard",
            "#028 [P] CollectaCard",
            "#029 [N] CollectaCard",
            "#029 [R] CollectaCard",
            "#029 [P] CollectaCard",
            "#030 [N] CollectaCard",
            "#030 [R] CollectaCard",
            "#030 [P] CollectaCard",
            "#031 [N] CollectaCard",
            "#031 [R] CollectaCard",
            "#031 [P] CollectaCard",
            "#032 [N] CollectaCard",
            "#032 [R] CollectaCard",
            "#032 [P] CollectaCard",
            "#033 [N] CollectaCard",
            "#033 [R] CollectaCard",
            "#033 [P] CollectaCard",
            "#034 [N] CollectaCard",
            "#034 [R] CollectaCard",
            "#034 [P] CollectaCard",
            "#035 [N] CollectaCard",
            "#035 [R] CollectaCard",
            "#035 [P] CollectaCard",
            "#036 [N] CollectaCard",
            "#036 [R] CollectaCard",
            "#036 [P] CollectaCard",
            "#037 [N] CollectaCard",
            "#037 [R] CollectaCard",
            "#037 [P] CollectaCard",
            "#038 [N] CollectaCard",
            "#038 [R] CollectaCard",
            "#038 [P] CollectaCard",
            "#039 [N] CollectaCard",
            "#039 [R] CollectaCard",
            "#039 [P] CollectaCard",
            "#040 [N] CollectaCard",
            "#040 [R] CollectaCard",
            "#040 [P] CollectaCard",
            "#041 [N] CollectaCard",
            "#041 [R] CollectaCard",
            "#041 [P] CollectaCard",
            "#042 [N] CollectaCard",
            "#042 [R] CollectaCard",
            "#042 [P] CollectaCard",
            "#043 [N] CollectaCard",
            "#043 [R] CollectaCard",
            "#043 [P] CollectaCard",
            "#044 [N] CollectaCard",
            "#044 [R] CollectaCard",
            "#044 [P] CollectaCard",
            "#045 [N] CollectaCard",
            "#045 [R] CollectaCard",
            "#045 [P] CollectaCard",
            "#046 [N] CollectaCard",
            "#046 [R] CollectaCard",
            "#046 [P] CollectaCard",
            "#047 [N] CollectaCard",
            "#047 [R] CollectaCard",
            "#047 [P] CollectaCard",
            "#048 [N] CollectaCard",
            "#048 [R] CollectaCard",
            "#048 [P] CollectaCard",
            "#049 [N] CollectaCard",
            "#049 [R] CollectaCard",
            "#049 [P] CollectaCard",
            "#050 [N] CollectaCard",
            "#050 [R] CollectaCard",
            "#050 [P] CollectaCard",
            "#051 [N] CollectaCard",
            "#051 [R] CollectaCard",
            "#051 [P] CollectaCard",
            "#052 [N] CollectaCard",
            "#052 [R] CollectaCard",
            "#052 [P] CollectaCard",
            "#053 [N] CollectaCard",
            "#053 [R] CollectaCard",
            "#053 [P] CollectaCard",
            "#054 [N] CollectaCard",
            "#054 [R] CollectaCard",
            "#054 [P] CollectaCard",
            "#055 [N] CollectaCard",
            "#055 [R] CollectaCard",
            "#055 [P] CollectaCard",
            "#056 [N] CollectaCard",
            "#056 [R] CollectaCard",
            "#056 [P] CollectaCard",
            "#057 [N] CollectaCard",
            "#057 [R] CollectaCard",
            "#057 [P] CollectaCard",
            "#058 [N] CollectaCard",
            "#058 [R] CollectaCard",
            "#058 [P] CollectaCard",
            "#059 [N] CollectaCard",
            "#059 [R] CollectaCard",
            "#059 [P] CollectaCard",
            "#060 [N] CollectaCard",
            "#060 [R] CollectaCard",
            "#060 [P] CollectaCard",
            "#061 [N] CollectaCard",
            "#061 [R] CollectaCard",
            "#061 [P] CollectaCard",
            "#062 [N] CollectaCard",
            "#062 [R] CollectaCard",
            "#062 [P] CollectaCard",
            "#063 [N] CollectaCard",
            "#063 [R] CollectaCard",
            "#063 [P] CollectaCard",
            "#064 [N] CollectaCard",
            "#064 [R] CollectaCard",
            "#064 [P] CollectaCard",
            "#065 [N] CollectaCard",
            "#065 [R] CollectaCard",
            "#065 [P] CollectaCard",
            "#066 [N] CollectaCard",
            "#066 [R] CollectaCard",
            "#066 [P] CollectaCard",
            "#067 [N] CollectaCard",
            "#067 [R] CollectaCard",
            "#067 [P] CollectaCard",
            "#068 [N] CollectaCard",
            "#068 [R] CollectaCard",
            "#068 [P] CollectaCard",
            "#069 [N] CollectaCard",
            "#069 [R] CollectaCard",
            "#069 [P] CollectaCard",
            "#070 [N] CollectaCard",
            "#070 [R] CollectaCard",
            "#070 [P] CollectaCard",
            "#071 [N] CollectaCard",
            "#071 [R] CollectaCard",
            "#071 [P] CollectaCard",
            "#072 [N] CollectaCard",
            "#072 [R] CollectaCard",
            "#072 [P] CollectaCard",
            "#073 [N] CollectaCard",
            "#073 [R] CollectaCard",
            "#073 [P] CollectaCard",
            "#074 [N] CollectaCard",
            "#074 [R] CollectaCard",
            "#074 [P] CollectaCard",
            "#075 [N] CollectaCard",
            "#075 [R] CollectaCard",
            "#075 [P] CollectaCard",
            "#076 [N] CollectaCard",
            "#076 [R] CollectaCard",
            "#076 [P] CollectaCard",
            "#077 [N] CollectaCard",
            "#077 [R] CollectaCard",
            "#077 [P] CollectaCard",
            "#078 [N] CollectaCard",
            "#078 [R] CollectaCard",
            "#078 [P] CollectaCard",
            "#079 [N] CollectaCard",
            "#079 [R] CollectaCard",
            "#079 [P] CollectaCard",
            "#080 [N] CollectaCard",
            "#080 [R] CollectaCard",
            "#080 [P] CollectaCard",
            "#081 [N] CollectaCard",
            "#081 [R] CollectaCard",
            "#081 [P] CollectaCard",
            "#082 [N] CollectaCard",
            "#082 [R] CollectaCard",
            "#082 [P] CollectaCard",
            "#083 [N] CollectaCard",
            "#083 [R] CollectaCard",
            "#083 [P] CollectaCard",
            "#084 [N] CollectaCard",
            "#084 [R] CollectaCard",
            "#084 [P] CollectaCard",
            "#085 [N] CollectaCard",
            "#085 [R] CollectaCard",
            "#085 [P] CollectaCard",
            "#086 [N] CollectaCard",
            "#086 [R] CollectaCard",
            "#086 [P] CollectaCard",
            "#087 [N] CollectaCard",
            "#087 [R] CollectaCard",
            "#087 [P] CollectaCard",
            "#088 [N] CollectaCard",
            "#088 [R] CollectaCard",
            "#088 [P] CollectaCard",
            "#089 [N] CollectaCard",
            "#089 [R] CollectaCard",
            "#089 [P] CollectaCard",
            "#090 [N] CollectaCard",
            "#090 [R] CollectaCard",
            "#090 [P] CollectaCard",
            "#091 [N] CollectaCard",
            "#091 [R] CollectaCard",
            "#091 [P] CollectaCard",
            "#092 [N] CollectaCard",
            "#092 [R] CollectaCard",
            "#092 [P] CollectaCard",
            "#093 [N] CollectaCard",
            "#093 [R] CollectaCard",
            "#093 [P] CollectaCard",
            "#094 [N] CollectaCard",
            "#094 [R] CollectaCard",
            "#094 [P] CollectaCard",
            "#095 [N] CollectaCard",
            "#095 [R] CollectaCard",
            "#095 [P] CollectaCard",
            "#096 [N] CollectaCard",
            "#096 [R] CollectaCard",
            "#096 [P] CollectaCard",
            "#097 [N] CollectaCard",
            "#097 [R] CollectaCard",
            "#097 [P] CollectaCard",
            "#098 [N] CollectaCard",
            "#098 [R] CollectaCard",
            "#098 [P] CollectaCard",
            "#099 [N] CollectaCard",
            "#099 [R] CollectaCard",
            "#099 [P] CollectaCard",
            "#100 [N] CollectaCard",
            "#100 [R] CollectaCard",
            "#100 [P] CollectaCard",
            "#101 [N] CollectaCard",
            "#101 [R] CollectaCard",
            "#101 [P] CollectaCard",
            "#102 [N] CollectaCard",
            "#102 [R] CollectaCard",
            "#102 [P] CollectaCard",
            "#103 [N] CollectaCard",
            "#103 [R] CollectaCard",
            "#103 [P] CollectaCard",
            "#104 [N] CollectaCard",
            "#104 [R] CollectaCard",
            "#104 [P] CollectaCard",
            "#105 [N] CollectaCard",
            "#105 [R] CollectaCard",
            "#105 [P] CollectaCard",
            "#106 [N] CollectaCard",
            "#106 [R] CollectaCard",
            "#106 [P] CollectaCard",
            "#107 [N] CollectaCard",
            "#107 [R] CollectaCard",
            "#107 [P] CollectaCard",
            "#108 [N] CollectaCard",
            "#108 [R] CollectaCard",
            "#108 [P] CollectaCard",
            "#109 [N] CollectaCard",
            "#109 [R] CollectaCard",
            "#109 [P] CollectaCard",
            "#110 [N] CollectaCard",
            "#110 [R] CollectaCard",
            "#110 [P] CollectaCard",
            "#111 [N] CollectaCard",
            "#111 [R] CollectaCard",
            "#111 [P] CollectaCard",
            "#112 [N] CollectaCard",
            "#112 [R] CollectaCard",
            "#112 [P] CollectaCard",
            "#113 [N] CollectaCard",
            "#113 [R] CollectaCard",
            "#113 [P] CollectaCard",
            "#114 [N] CollectaCard",
            "#114 [R] CollectaCard",
            "#114 [P] CollectaCard",
            "#115 [N] CollectaCard",
            "#115 [R] CollectaCard",
            "#115 [P] CollectaCard",
            "#116 [N] CollectaCard",
            "#116 [R] CollectaCard",
            "#116 [P] CollectaCard",
            "#117 [N] CollectaCard",
            "#117 [R] CollectaCard",
            "#117 [P] CollectaCard",
            "#118 [N] CollectaCard",
            "#118 [R] CollectaCard",
            "#118 [P] CollectaCard",
            "#119 [N] CollectaCard",
            "#119 [R] CollectaCard",
            "#119 [P] CollectaCard",
            "#120 [N] CollectaCard",
            "#120 [R] CollectaCard",
            "#120 [P] CollectaCard",
            "#121 [N] CollectaCard",
            "#121 [R] CollectaCard",
            "#121 [P] CollectaCard",
            "#122 [N] CollectaCard",
            "#122 [R] CollectaCard",
            "#122 [P] CollectaCard",
            "#123 [N] CollectaCard",
            "#123 [R] CollectaCard",
            "#123 [P] CollectaCard",
            "#124 [N] CollectaCard",
            "#124 [R] CollectaCard",
            "#124 [P] CollectaCard",
            "#125 [N] CollectaCard",
            "#125 [R] CollectaCard",
            "#125 [P] CollectaCard",
            "#126 [N] CollectaCard",
            "#126 [R] CollectaCard",
            "#126 [P] CollectaCard",
            "#127 [N] CollectaCard",
            "#127 [R] CollectaCard",
            "#127 [P] CollectaCard",
            "#128 [N] CollectaCard",
            "#128 [R] CollectaCard",
            "#128 [P] CollectaCard",
            "#129 [N] CollectaCard",
            "#129 [R] CollectaCard",
            "#129 [P] CollectaCard",
            "#130 [N] CollectaCard",
            "#130 [R] CollectaCard",
            "#130 [P] CollectaCard",
            "#131 [N] CollectaCard",
            "#131 [R] CollectaCard",
            "#131 [P] CollectaCard",
            "#132 [N] CollectaCard",
            "#132 [R] CollectaCard",
            "#132 [P] CollectaCard",
            "#133 [N] CollectaCard",
            "#133 [R] CollectaCard",
            "#133 [P] CollectaCard",
            "#134 [N] CollectaCard",
            "#134 [R] CollectaCard",
            "#134 [P] CollectaCard",
            "#135 [N] CollectaCard",
            "#135 [R] CollectaCard",
            "#135 [P] CollectaCard",
            "#136 [N] CollectaCard",
            "#136 [R] CollectaCard",
            "#136 [P] CollectaCard",
            "#137 [N] CollectaCard",
            "#137 [R] CollectaCard",
            "#137 [P] CollectaCard",
            "#138 [N] CollectaCard",
            "#138 [R] CollectaCard",
            "#138 [P] CollectaCard",
            "#139 [N] CollectaCard",
            "#139 [R] CollectaCard",
            "#139 [P] CollectaCard",
            "#140 [N] CollectaCard",
            "#140 [R] CollectaCard",
            "#140 [P] CollectaCard",
            "#141 [N] CollectaCard",
            "#141 [R] CollectaCard",
            "#141 [P] CollectaCard",
            "#142 [N] CollectaCard",
            "#142 [R] CollectaCard",
            "#142 [P] CollectaCard",
            "#143 [N] CollectaCard",
            "#143 [R] CollectaCard",
            "#143 [P] CollectaCard",
            "#144 [N] CollectaCard",
            "#144 [R] CollectaCard",
            "#144 [P] CollectaCard",
            "#145 [N] CollectaCard",
            "#145 [R] CollectaCard",
            "#145 [P] CollectaCard",
            "#146 [N] CollectaCard",
            "#146 [R] CollectaCard",
            "#146 [P] CollectaCard",
            "#147 [N] CollectaCard",
            "#147 [R] CollectaCard",
            "#147 [P] CollectaCard",
            "#148 [N] CollectaCard",
            "#148 [R] CollectaCard",
            "#148 [P] CollectaCard",
            "#149 [N] CollectaCard",
            "#149 [R] CollectaCard",
            "#149 [P] CollectaCard",
            "#150 [N] CollectaCard",
            "#150 [R] CollectaCard",
            "#150 [P] CollectaCard",
            "#151 [N] CollectaCard",
            "#151 [R] CollectaCard",
            "#151 [P] CollectaCard",
            "#152 [N] CollectaCard",
            "#152 [R] CollectaCard",
            "#152 [P] CollectaCard",
            "#153 [N] CollectaCard",
            "#153 [R] CollectaCard",
            "#153 [P] CollectaCard",
            "#154 [N] CollectaCard",
            "#154 [R] CollectaCard",
            "#154 [P] CollectaCard",
            "#155 [N] CollectaCard",
            "#155 [R] CollectaCard",
            "#155 [P] CollectaCard",
            "#156 [N] CollectaCard",
            "#156 [R] CollectaCard",
            "#156 [P] CollectaCard",
            "#157 [N] CollectaCard",
            "#157 [R] CollectaCard",
            "#157 [P] CollectaCard",
            "#158 [N] CollectaCard",
            "#158 [R] CollectaCard",
            "#158 [P] CollectaCard",
            "#159 [N] CollectaCard",
            "#159 [R] CollectaCard",
            "#159 [P] CollectaCard",
            "#160 [N] CollectaCard",
            "#160 [R] CollectaCard",
            "#160 [P] CollectaCard",
            "#161 [N] CollectaCard",
            "#161 [R] CollectaCard",
            "#161 [P] CollectaCard",
            "#162 [N] CollectaCard",
            "#162 [R] CollectaCard",
            "#162 [P] CollectaCard",
            "Red Shard",
            "Indigo Shard",
            "Yellow Shard",
            "Green Shard",
            "Peach Shard",
            "Purple Shard",
            "Orange Shard",
            "Turquoise Shard",
            "White Shard",
            "Golden Shard",
            "Silver Shard",
            "Black Shard"
        };

        public static string[] characters = new string[]
        {
            "Warrior of Light",
            "Firion",
            "Onion Knight",
            "Cecil",
            "Kain",
            "Bartz",
            "Terra",
            "Cloud",
            "Sephiroth",
            "Squall",
            "Zidane",
            "Tidus",
            "Shantotto",
            "Vaan",
            "Lightning",
            "Princess Sarah",
            "Minwu",
            "Cid",
            "Rydia",
            "Faris",
            "Locke",
            "Aerith",
            "Seifer",
            "Vivi",
            "Yuna",
            "Prishe",
            "Ashe",
            "Snow",
            "Cosmos",
            "Edge",
            "Lenna",
            "Galuf",
            "Celes",
            "Edgar",
            "Tifa",
            "Barret",
            "Rinoa",
            "Laguna",
            "Garnet",
            "Eiko",
            "Auron",
            "Jecht",
            "Aphmau",
            "Lilisette",
            "Balthier",
            "Fran",
            "Hope",
            "Vanille",
            "Y'shtola",
            "Chaos",
            "Ace",
            "Machina",
            "Rem",
            "Ramza",
            "Agrias",
            "Benjamin",
            "Ciaran",
            "Yuna #2",
            "Rikku",
            "Paine",
            "Serah",
            "Noel",
            "Lightning #2",
            "Tifa #2",
            "Zack",
            "Yuffie",
            "Rosa",
            "Cloud #2",
            "Orlandeau",
            "Auron #2",
            "Vincent"
        };
    }
}
